### Register User
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "syaifudin",
  "phone": "085123456789",
  "email": "syaifudin@gmail.com",
  "password": "rahasia123"
}

### Register User Bad Request
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "",
  "phone": "085123456789",
  "email": "syaifudin@gmail.com",
  "password": "rahasia123"
}


### Get User By Id
GET http://localhost:8080/api/users/1

### Get User Not Found
GET http://localhost:8080/api/users/100000
